name: 'lint-pr'
on:
  # by adding a schedule task to this workflow we will automatically
  # begin serializing read-only runs and handling them. The cron job
  # below is set to run every 15 minutes, GitHub will ignore anything
  # under 10 minutes and run every 10 minutes anyway.

  # re-enable this once the repo is public
  
  # schedule:
  #   - cron: '*/60 * * * *'
  pull_request:
    branches: [ main, beta, alpha ]
    types:
      - opened
      - synchronize
      - closed
env:
  GITHUB_TOKEN: ${{ secrets.BOT_GIT_TOKEN }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bradennapier/eslint-plus-action@v3.4.0
        with:
          # The follow should be considered
          reportWarningsAsErrors: true
          issueSummaryOnlyOnEvent: true
